### ISSUE TITLE
Can't get completion and documentation for some package commands

### ISSUE THREAD

**Issue by liushihao456** [astoff/digestif#20]
Hi! I am on macOS Mojave, and installed digestif via luarocks. However I can't seem to get completions for commands of some packages, e.g. listings, amsmath. But commands like ```\def```, ```\usepackage``` get completions fine.
<img width="395" alt="屏幕快照 2020-04-04 11 24 21" src="https://user-images.githubusercontent.com/28855328/78417716-6a93c680-7667-11ea-8d91-02fa491d2758.png">
I expect to have a popup completion menu containing lstset{}.... Is there something I should do in configuration to make digestif work as expected? Thanks!

**Comment by astoff** [comment]
This happens because there is no data file for these packages yet. Unfortunately, since (La)TeX has free-form manuals rather than a systematic documentation system, creating those data files is, to a large degree, a manual process. (The rationale for not using a more automatic approach is explained [here](https://github.com/astoff/digestif/issues/19).)

I agree that the mentioned packages are among the high-priority ones, and I might get to them sometime. Obviously, contributions are always welcome :-)

**Comment by astoff** [comment]
The current master version is able to parse the locally installed packages and learn about the commands they define. This depends on the `tlmgr` command for now. It's not perfect, but works with amsmath, for instance.

@liushihao456 Let me know if you get a chance to test this.
