### ISSUE TITLE
/home/user/.digestif/bin/digestif:2: in main chunk

### ISSUE THREAD

**Issue by liar666** [astoff/digestif#31]
Hi,

I'm trying to run digestif so that I can get LSP under Emacs on my OpenBSD box.

When I go to `~/.digestif` and run `./bin/digestif`, nothing happens, but the program does not end, which seems good to me for a (language)-server.

However, when I open a `.tex` file in Emacs and do `M-x lsp` it tells me lsp server did not run correctly and buffer `digestif::stderr` says:
```
stack traceback:
	[C]: in function 'require'
	/home/user/.digestif/bin/digestif:2: in main chunk
	[C]: in ?

Process digestif stderr<1> finished

Process digestif stderr finished
```

Do do not know anything about `lua` and this message does not help me much.

Any idea?

NOTE: I apparently have `lua51` and `lua53` installed

EDIT: running `./bin/digestif -v` gives me `22:02:12 Digestif started!` so everything seems OK outside Emacs.

**Comment by astoff** [comment]
Which installation method did you use? What happens if you run `digestif -v` in the home directory without specifying a path (that's what Emacs will do)?

**Comment by RaulPPelaez** [comment]
Hi, I get similar errors, I installed using the script provided in the README.md.
This is the output of running digestif -v  

```
lua: /home/user/.digestif/bin/digestif:2: module 'digestif.langserver' not found:
	no field package.preload['digestif.langserver']
	no file '/usr/share/lua/5.4/digestif/langserver.lua'
	no file '/usr/share/lua/5.4/digestif/langserver/init.lua'
	no file '/usr/lib64/lua/5.4/digestif/langserver.lua'
	no file '/usr/lib64/lua/5.4/digestif/langserver/init.lua'
	no file './digestif/langserver.lua'
	no file './digestif/langserver/init.lua'
	no file '/usr/lib64/lua/5.4/digestif/langserver.so'
	no file '/usr/lib64/lua/5.4/loadall.so'
	no file './digestif/langserver.so'
	no file '/usr/lib64/lua/5.4/digestif.so'
	no file '/usr/lib64/lua/5.4/loadall.so'
	no file './digestif.so'
stack traceback:
	[C]: in function 'require'
	/home/user/.digestif/bin/digestif:2: in main chunk
	[C]: in ?
```
I tried using luarocks, but the installation fails because of an unmet dependency (dkjson). I am in Fedora 33, which ships with lua 5.4.

If I change lua by texlua [here](https://github.com/astoff/digestif/blob/master/bin/digestif#L1) the server runs, but only if I launch it from the $HOME/.digestif/ directory. Running it outside this folder gets me the same error above.

Finally, setting the LUA_PATH variable to this (in addition to the aforementioned change to .digestif/bin/digestif):
```$ export LUA_PATH=/home/user/.digestif/?.lua```

Makes the server run without apparent issues.

**Comment by astoff** [comment]
@RaulPPelaez Are you sure you are calling the bash script, and not the `bin/digestif` Lua script directly? You can check this by typing `which digestif` in a terminal.

**Comment by astoff** [comment]
Since there was no reply in a several months, I'll close this.

**Comment by yugaego** [comment]
> digestif:2: module 'digestif.langserver' not found:

I had the same error having `lua` installed and [apparently wrongly](https://github.com/astoff/digestif/issues/31#issuecomment-808021687) relying on `digestif` from source directly.

The issue was fixed in my case by installing `luarocks`, and then using `digestif` installed by `luarocks`.

Though I'm sure the already mentioned bash script approach should work too.

**Comment by astoff** [comment]
Just to make sure: if you follow the i, ii, iii steps in the "For LuaTeX with the self-installing script" section of the README, it just works, no?
